export const CURATED_TOPICS = [
  'fiction',
  'non-fiction',
  'philosophy',
  'psychology',
  'history',
  'science',
  'technology',
  'mathematics',
  'economics',
  'politics',
  'sociology',
  'anthropology',
  'systems-thinking',
  'complexity',
  'cybernetics',
  'design',
  'architecture',
  'urbanism',
  'ecology',
  'spirituality',
  'mysticism',
  'religion',
  'poetry',
  'memoir',
  'biography',
  'essays',
  'science-fiction',
  'fantasy',
  'literary-fiction',
  'classics',
  'education',
  'pedagogy',
  'parenting',
  'self-help',
  'business',
  'management',
  'leadership',
  'creativity',
  'art',
  'music',
  'film',
  'photography',
  'cooking',
  'travel',
  'nature',
  'health',
  'fitness',
  'mindfulness',
  'ethics',
  'law',
] as const;

export type CuratedTopic = typeof CURATED_TOPICS[number];

const SUBJECT_TO_TOPIC: Record<string, CuratedTopic> = {
  'philosophy': 'philosophy',
  'philosophical': 'philosophy',
  'psychology': 'psychology',
  'psychological': 'psychology',
  'history': 'history',
  'historical': 'history',
  'science': 'science',
  'scientific': 'science',
  'technology': 'technology',
  'computer': 'technology',
  'mathematics': 'mathematics',
  'mathematical': 'mathematics',
  'economics': 'economics',
  'economic': 'economics',
  'politics': 'politics',
  'political': 'politics',
  'sociology': 'sociology',
  'social': 'sociology',
  'anthropology': 'anthropology',
  'systems': 'systems-thinking',
  'complexity': 'complexity',
  'design': 'design',
  'architecture': 'architecture',
  'urban': 'urbanism',
  'ecology': 'ecology',
  'spiritual': 'spirituality',
  'mysticism': 'mysticism',
  'religion': 'religion',
  'religious': 'religion',
  'poetry': 'poetry',
  'poems': 'poetry',
  'memoir': 'memoir',
  'biography': 'biography',
  'fiction': 'fiction',
  'novel': 'fiction',
  'science fiction': 'science-fiction',
  'fantasy': 'fantasy',
  'education': 'education',
  'pedagogy': 'pedagogy',
  'business': 'business',
  'management': 'management',
  'leadership': 'leadership',
  'art': 'art',
  'music': 'music',
  'film': 'film',
  'ethics': 'ethics',
  'moral': 'ethics',
};

export function inferTopicsFromSubjects(subjects: string[]): CuratedTopic[] {
  const inferred = new Set<CuratedTopic>();

  for (const subject of subjects) {
    const lower = subject.toLowerCase();
    for (const [keyword, topic] of Object.entries(SUBJECT_TO_TOPIC)) {
      if (lower.includes(keyword)) {
        inferred.add(topic);
      }
    }
  }

  return Array.from(inferred);
}
